apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: events-guard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/${DOCKER_USERNAME}/ng-events-guard:${GITHUB_SHA}
        ports:
        - containerPort: 80
